In [11]:
import datetime
import numpy as np
import pandas as pd
from dateutil.relativedelta import relativedelta


"""taking inputs from user"""

annual_interest_rate = float(input('Annual Interest Rate(in decimals): '))
years = int(input('No. of years: '))
yearly_installments = int(input('Number of installments per year: '))
principal = float(input('Principal: '))
additional_principal = float(input('Additional Principal: '))
start_date = input('Start Date(Jan 1 2016): ')

"""Creation of table content"""

installment_date = datetime.datetime.strptime(start_date, '%b %d %Y').date()

installment_interest_rate = annual_interest_rate / yearly_installments
each_installment = -np.round(np.pmt(installment_interest_rate, yearly_installments * years, principal), 2)

final_unpaid_balance = principal

schedule_table = []
iteration = 1

while final_unpaid_balance > 0: 
    
    """part of installment amount that goes towards interest"""
    interest_amount = round(installment_interest_rate * final_unpaid_balance, 2)

    """calculating this installment amount"""
    this_installment = round(min(each_installment, interest_amount + final_unpaid_balance), 2)

    """part of installment that goes to main loan amount"""
    principal_amount = round(this_installment - interest_amount, 2)

    """adjustment with additional principal"""
    this_additional_principal = min(additional_principal, final_unpaid_balance - principal_amount)

    """ final loan balance"""
    final_unpaid_balance = round(final_unpaid_balance - (this_additional_principal + principal_amount), 2)

    """adding details of current installment payment"""
    installment_date_formatted = datetime.datetime.strftime(installment_date, '%Y-%m-%d')
    
    new_entry = [iteration, installment_date_formatted, this_installment, principal_amount, interest_amount,
                 this_additional_principal, final_unpaid_balance]
    
    schedule_table.append(new_entry)
    
    iteration += 1
    installment_date = installment_date + relativedelta(months=int(12 / yearly_installments))



column= ['Period','Payment_Date', 'Payment', 'Principal', 'Interest', 'Addl_Principal', 'Balance']

df= pd.DataFrame(schedule_table, columns= column)
df

Annual Interest Rate(in decimals): 0.04
No. of years: 30
Number of installments per year: 12
Principal: 200000
Additional Principal: 50
Start Date(Jan 1 2016): Jan 1 2016

,Period,Payment_Date,Payment,Principal,Interest,Addl_Principal,Balance
0,1,2016-01-01,954.83,288.16,666.67,50.0,199661.84
1,2,2016-02-01,954.83,289.29,665.54,50.0,199322.55
2,3,2016-03-01,954.83,290.42,664.41,50.0,198982.13
3,4,2016-04-01,954.83,291.56,663.27,50.0,198640.57
4,5,2016-05-01,954.83,292.69,662.14,50.0,198297.88
5,6,2016-06-01,954.83,293.84,660.99,50.0,197954.04
6,7,2016-07-01,954.83,294.98,659.85,50.0,197609.06
7,8,2016-08-01,954.83,296.13,658.70,50.0,197262.93
8,9,2016-09-01,954.83,297.29,657.54,50.0,196915.64
9,10,2016-10-01,954.83,298.44,656.39,50.0,196567.20
10,11,2016-11-01,954.83,299.61,655.22,50.0,196217.59
11,12,2016-12-01,954.83,300.77,654.06,50.0,195866.82
12,13,2017-01-01,954.83,301.94,652.89,50.0,195514.88
13,14,2017-02-01,954.83,303.11,651.72,50.0,195161.77
14,15,2017-03-01,954.83,304.29,650.54,50.0,194807.48
15,16,2017-04-01,954.83,305.47,649.36,50.0,194452.01
16,17,2017-05-01,954.83,306.66,648.17,50.0,194095.35
17,18,2017-06-01,954.83,307.85,646.98,50.0,193737.50
18,19,2017-07-01,954.83,309.04,645.79,50.0,193378.46
19,20,2017-08-01,954.83,310.24,644.59,50.0,193018.22
20,21,2017-09-01,954.83,311.44,643.39,50.0,192656.78
21,22,2017-10-01,954.83,312.64,642.19,50.0,192294.14
22,23,2017-11-01,954.83,313.85,640.98,50.0,191930.29
23,24,2017-12-01,954.83,315.06,639.77,50.0,191565.23
24,25,2018-01-01,954.83,316.28,638.55,50.0,191198.95
25,26,2018-02-01,954.83,317.50,637.33,50.0,190831.45
26,27,2018-03-01,954.83,318.73,636.10,50.0,190462.72
27,28,2018-04-01,954.83,319.95,634.88,50.0,190092.77
28,29,2018-05-01,954.83,321.19,633.64,50.0,189721.58
29,30,2018-06-01,954.83,322.42,632.41,50.0,189349.16
...,...,...,...,...,...,...,...
298,299,2040-11-01,954.83,861.61,93.22,50.0,27054.84
299,300,2040-12-01,954.83,864.65,90.18,50.0,26140.19
300,301,2041-01-01,954.83,867.70,87.13,50.0,25222.49
301,302,2041-02-01,954.83,870.76,84.07,50.0,24301.73
302,303,2041-03-01,954.83,873.82,81.01,50.0,23377.91
303,304,2041-04-01,954.83,876.90,77.93,50.0,22451.01
304,305,2041-05-01,954.83,879.99,74.84,50.0,21521.02
305,306,2041-06-01,954.83,883.09,71.74,50.0,20587.93
306,307,2041-07-01,954.83,886.20,68.63,50.0,19651.73
307,308,2041-08-01,954.83,889.32,65.51,50.0,18712.41
308,309,2041-09-01,954.83,892.46,62.37,50.0,17769.95
309,310,2041-10-01,954.83,895.60,59.23,50.0,16824.35
310,311,2041-11-01,954.83,898.75,56.08,50.0,15875.60
311,312,2041-12-01,954.83,901.91,52.92,50.0,14923.69
312,313,2042-01-01,954.83,905.08,49.75,50.0,13968.61
313,314,2042-02-01,954.83,908.27,46.56,50.0,13010.34
314,315,2042-03-01,954.83,911.46,43.37,50.0,12048.88
315,316,2042-04-01,954.83,914.67,40.16,50.0,11084.21
316,317,2042-05-01,954.83,917.88,36.95,50.0,10116.33
317,318,2042-06-01,954.83,921.11,33.72,50.0,9145.22
318,319,2042-07-01,954.83,924.35,30.48,50.0,8170.87
319,320,2042-08-01,954.83,927.59,27.24,50.0,7193.28
320,321,2042-09-01,954.83,930.85,23.98,50.0,6212.43
321,322,2042-10-01,954.83,934.12,20.71,50.0,5228.31
322,323,2042-11-01,954.83,937.40,17.43,50.0,4240.91
323,324,2042-12-01,954.83,940.69,14.14,50.0,3250.22
324,325,2043-01-01,954.83,944.00,10.83,50.0,2256.22
325,326,2043-02-01,954.83,947.31,7.52,50.0,1258.91
326,327,2043-03-01,954.83,950.63,4.20,50.0,258.28
327,328,2043-04-01,259.14,258.28,0.86,0.0,0.00